spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false # 프로젝트 구동 시점이 아닌, scheduling으로 batch를 실행시킨다.
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
